### ISSUE TITLE
Fix frequency range (it's 150 Hz to 3750 Hz according to  ITU-T V.34)

### ISSUE THREAD

**Issue by VasylSamoilov** [ktownsend-personal/RetroPhone#4]
Wikipedia is not exactly correct stating what analog phone lines are 300-3400 Hz. It's sufficient for voice call, but not the standard.
Documentation should be fixed in order not to fall into VoIP trap (most VoIP devices do hard cut-off at 3400, which is terrible)
Range should be at least 150 to 3750 Hz. Given that we are not restricted with standards, it's safe to implement 150-4000Hz range.
Frequencies lower that 150Hz are affected with power line noise anyway.

If modems are to be any indicator of phone line quality (and modems really used all that was available), then it's best to refer to V.34 standard, section that describes line quality probing is the most useful:
 
Line probing signal sender and receiver based on ITU-T V.34 TELECOMMUNICATION STANDARDIZATION SECTOR
OF ITU (02/98) https://www.itu.int/rec/T-REC-V.34, section 10.1.2.4 Line probing signals (page 31):

Quote: "Two line probing signals, L1 and L2, are used to analyse channel characteristics. L1 is a periodic signal with a repetition
rate of 150 ± 0.01% Hz which consists of a set of tones (cosines) spaced 150 Hz apart at frequencies from 150 Hz
to 3750 Hz. Tones at 900 Hz, 1200 Hz, 1800 Hz, and 2400 Hz are omitted. The initial phase of each cosine is given in
Table 17. L1 is transmitted for 160 ms (24 repetitions) at 6 dB above the nominal power level. L2 is the same as L1 but is
transmitted for no longer than 550 ms plus a round trip delay at the nominal power level."

output line characteristics from USR Courier modems for V.34 calls (note the frequency range):

example 1: perfect analog line (real analog pbx):

```Recv/Xmit Level (-dBm)   17.0/13.3
SNR             ( dB )   45.4
Near Echo Loss  ( dB )   17.5
Far Echo Loss   ( dB )   59.3
Roundtrip Delay (msec)   0

 -16  . . x x x x x x x x x x x x x x x x x x x x x . .   0
 -18  . X X X X X X X X X X X X X X X X X X X X X X X X   2
 -20  . X X X X X X X X X X X X X X X X X X X X X X X X   4
 -22  X X X X X X X X X X X X X X X X X X X X X X X X X   6
Level --------------------Frequency-------------------- Attn
      0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3
      1 3 4 6 7 9 0 2 3 5 6 8 9 1 2 4 5 7 8 0 1 3 4 6 7
      5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

```

Example 2: Call via asterisk (cutoff at 300 Hz and about 3300 Hz due to implementation, transcoding, level mismatch, roundtrip delay):

```
Recv/Xmit Level (-dBm)   19.6/13.3
SNR             ( dB )   39.9
Near Echo Loss  ( dB )   15.1
Far Echo Loss   ( dB )   50.5
Roundtrip Delay (msec)   9

 -18  . . x x x x x x x x x x x x x x x . . . . . . . .   0
 -20  . X X X X X X X X X X X X X X X X X X X X X . . .   2
 -22  . X X X X X X X X X X X X X X X X X X X X X . . .   4
 -24  . X X X X X X X X X X X X X X X X X X X X X x . .   6
 -26  . X X X X X X X X X X X X X X X X X X X X X X . .   8
 -28  . X X X X X X X X X X X X X X X X X X X X X X . .  10
 -30  . X X X X X X X X X X X X X X X X X X X X X X . .  12
 -32  . X X X X X X X X X X X X X X X X X X X X X X . .  14
 -34  X X X X X X X X X X X X X X X X X X X X X X X x .  16
 -36  X X X X X X X X X X X X X X X X X X X X X X X X .  18
 -38  X X X X X X X X X X X X X X X X X X X X X X X X .  20
 -40  X X X X X X X X X X X X X X X X X X X X X X X X .  22
 -42  X X X X X X X X X X X X X X X X X X X X X X X X .  24
 -44  X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=.  26
Level --------------------Frequency-------------------- Attn
      0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3
      1 3 4 6 7 9 0 2 3 5 6 8 9 1 2 4 5 7 8 0 1 3 4 6 7
      5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5 0 5
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by ktownsend-personal** [comment]
@VasylSamoilov thanks for that reference. I plan to use modems on this at some point so that full range will be important.

**Comment by ktownsend-personal** [comment]
I have updated one reference in the main readme file. When I get back to designing the audio filters I will be sure to account for this updated range. Thanks again.
